sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -m gemma -s 1 -a colors
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -m gemma -s 1 -a foods
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -m gemma -s 1 -a cars
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -m gemma -s 1 -a stocks
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -m gemma -s 1 -a laptops
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -m gemma -s 1 -a laptop_brands
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -m gemma -s 4 -a colors
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -m gemma -s 4 -a foods
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -m gemma -s 4 -a cars
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -m gemma -s 4 -a stocks
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -m gemma -s 4 -a laptops
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -m gemma -s 4 -a laptop_brands
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -m gemma -s 12 -a colors
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -m gemma -s 12 -a foods
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -m gemma -s 12 -a cars
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -m gemma -s 12 -a stocks
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -m gemma -s 12 -a laptops
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -m gemma -s 12 -a laptop_brands
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -m gemma -s 27 -a colors
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -m gemma -s 27 -a foods
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -m gemma -s 27 -a cars
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -m gemma -s 27 -a stocks
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -m gemma -s 27 -a laptops
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -m gemma -s 27 -a laptop_brands
