sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -a colors -m qwen -s 0.5
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -a foods -m qwen -s 0.5
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -a cars -m qwen -s 0.5
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -a stocks -m qwen -s 0.5
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -a laptops -m qwen -s 0.5
sbatch -p bml -A bml -w plato1 scripts/run_data_collection.sh -a laptop_brands -m qwen -s 0.5
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -a colors -m qwen -s 7
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -a foods -m qwen -s 7
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -a cars -m qwen -s 7
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -a stocks -m qwen -s 7
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -a laptops -m qwen -s 7
sbatch -p bml -A bml -w plato2 scripts/run_data_collection.sh -a laptop_brands -m qwen -s 7
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -a colors -m qwen -s 32
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -a foods -m qwen -s 32
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -a cars -m qwen -s 32
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -a stocks -m qwen -s 32
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -a laptops -m qwen -s 32
sbatch -p bml -A bml -w plotinus1 scripts/run_data_collection.sh -a laptop_brands -m qwen -s 32
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -a colors -m qwen -s 72
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -a foods -m qwen -s 72
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -a cars -m qwen -s 72
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -a stocks -m qwen -s 72
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -a laptops -m qwen -s 72
sbatch -p bml -A bml -w plotinus2 scripts/run_data_collection.sh -a laptop_brands -m qwen -s 72
